version: '3.7'
services:
  mongo:
    image: mongo    
    container_name: mongo    
    volumes:      
      - mongodata:/data/db
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
  roulette-api:
    container_name: roulette-api
    image: rouletteapi
    build:
      context: ./roulette.api
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
    depends_on:
      - mongo
volumes:
  mongodata: