@url = https://localhost:5001/api

### --- Gets one random Phrase --- ###
# @name getNRandomPhrase
GET {{url}}/roulette HTTP/1.1

### --- Gets First N Phrase --- ###
# @name getFirstNPhrase
GET {{url}}/roulette/first/3 HTTP/1.1

### --- Gets Last N Phrase --- ###
# @name getLastNPhrase
GET {{url}}/roulette/last/3 HTTP/1.1


### --- Gets Phrases by Id --- ###
# @name getPhraseById
GET {{url}}/roulette/getbyid/5cceebaecf3eb90001b818a0 HTTP/1.1


### --- Creates a Phrase --- ###
# @createPhrase
POST {{url}}/roulette HTTP/1.1
Content-Type:application/json

{
    "key": "A bird in the hand is worth two in the bush",
    "value": "Means it's better to have the certainty of a small thing than the possibility of something greater which may come to nothing."
}